[package]
name = "orientdb"
version = "0.1.0"
authors = ["Enrico Risa <enrico.risa@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.7"
byteorder = "1.3.2"
r2d2 = "0.8.5"
nom = "5.0.0"




[dev-dependencies]
dotenv = "0.14.1"