language: rust
sudo: required
services:
  - docker


rust:
  - stable
  - nightly


addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev


env:
  - ORIENTDB_VERSION=3.0.22

before_install:
  - rustup component add rustfmt
  - cargo fmt --all -- --check

script:
  - cargo test --all

before_script:
  - docker-compose -f docker-compose/docker-compose.yaml up -d 

after_script:
  - docker-compose -f docker-compose/docker-compose.yml down --remove-orphans


